# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zRuzSNDD_jdjB3nUbDBPWoRUOYgRHHr0
"""

First_name=input("Enter your first name:") 
Last_name=input("Enter last  name:")
print("Full name:",Last_name,First_name)

R=int(input("Enter Radius:"))
A=3.142*pow(R,2)
print("The area of circle is:",A)

Example=input("Enter anything with commas:")
print(Example.split(","))

exam_st_date=29"/"2"/"2022
print("The examination will start from:"+str(exam_st_date))

print("This")
print("is a.....multi-line")
print("heredoc string --------> example")

n=int(input("Enter integer value:"))
integer=n+n*n+n*n*n
print("Result:"+str(integer))

radius=6
r=pow(radius,3)
v=4/3*3.142*r
print("The volume of sphere is:"+str(v))

subjects=["English","Maths","Science","Urdu"]
print("Fav :",subjects[2])

cities=["karachi","islamabad","lahore"]
cities.append("multan")
print(cities)

cities=["karachi","islamabad","lahore"]
cities.insert(2,"multan")
print(cities)

cities=["karachi","islamabad","lahore","multan","sukkur"]
short=cities[1:3]
print(short)

cities=["karachi","islamabad","lahore","multan","sukkur"]
short=cities[ :3]
print(short)

cities=["karachi","islamabad","lahore","multan","sukkur"]
short=cities[2: ]
print(short)

cities=["karachi","islamabad","lahore","multan","sukkur"]
cities.reverse()
cities[:]

cities=["karachi","islamabad","lahore","multan","sukkur"]
del cities[2]
print(cities)

cities=["karachi","islamabad","lahore","multan","sukkur"]
cities.remove("lahore")
print(cities)

names=[]
a=input("Enter 1st name: ")
b=input("Enter 2nd name: ")
c=input("Enter 3rd name: ")
names.append(a)
names.append(b)
names.append(c)
print(names)

cities=["karachi","islamabad","lahore","multan","sukkur"]
cities.sort()
print(cities)
cities.sort(reverse=True)
print(cities)

name1=input("Enter 1st name: ")
name2=input("Enter 2nd name: ")
print(name1[1: ]+name2[1: ])

cities=["karachi","islamabad","lahore","multan","sukkur","Rawalpindi","Gujrat","Jacobabad","Nawabshah","hydrabad"]
cities.sort()
print(cities)

cities.sort(reverse=True)
print(cities)

print(sorted(cities))
print(sorted(cities, reverse=True))

slicing=cities[3:8]
print(slicing)

